### PR TITLE
Update IpAddr.hpp

### PR DESCRIPTION
**Pull request by alessandromrc**
- added method isPrivateIp to check if the ip address is within private ranges
- convert automatically "localhost" to 127.0.0.1

### CODE REVIEW

**Comment by Sainan** [comment]
- Checking IP ranges should be done properly by using CIDR. I can implement that one of these days, I guess.
- What reason do you have for wanting "localhost" to be valid in the IpAddr constructor? To resolve names like localhost, you can use `dnsOsResolver::lookupIPv4`

**Comment by alessandromrc** [comment]
> - Checking IP ranges should be done properly by using CIDR. I can implement that one of these days, I guess.
> 
> - What reason do you have for wanting "localhost" to be valid in the IpAddr constructor? To resolve names like localhost, you can use `dnsOsResolver::lookupIPv4`

It would be nice if you could implement the range check using CIDR and also I didn't know about using the dns resolver to resolve localhost, also sometimes it would be greater to resolve it in IpAddr like when making a UDP/TCP socketed (Still I can see why you would prefer the DNS way as if the user changed the localhost address it would automatically resolve to the correct one)

Ps. Having the possiblity to have IP ranges in an array would be useful (from IP to IP).

**Comment by Sainan** [comment]
Pushed. IpAddr::isLocalnet should be about the same as isPrivateIp.

Also would be somewhat good to know what problems you're trying to solve so I can see if there's not a better solution.

**Comment by alessandromrc** [comment]
I'm actually not developing anything, I just wanted to add more things to Soup just for the sake of it 😊

**Pull request closed without merging**
